env: Production
server:
  port: 8080
  
app:
  version: @project.version@
  shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,/js/main.js,/js/access-sphere.js,*/img/*,*/favicon.ico,*/index.html,*/documentation/*,*/error.html,/config/config.js"

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,/js/main.js,/js/access-sphere.js,*/img/*,*/favicon.ico,*/index.html,*/documentation/*,*/error.html,/config/config.js"

rest:
  client:
    access-sphere:
      client-id: TAX-CALCULATOR-01
      baseUrl: http://access.sphere.service:8080
      userInfo: /v1/userInfo

logging:
  config: classpath:logback-google.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    io.github.giovannilamarmora: ${LOGGING_LEVEL}