env: ${APP_ENV:Local} # Used for Google Cloud LOG
server:
  port: 8085
spring:
  application:
    name: Tax-Calculator
    starter-log: true
app:
  version: @project.version@
  shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,/js/main.js,/js/access-sphere.js,*/img/*,*/favicon.ico,*/index.html,*/documentation/*,*/error.html,/config/config.js"
  exception:
    stacktrace: true # Active StackTrace in Response

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,/js/main.js,/js/access-sphere.js,*/img/*,*/favicon.ico,*/index.html,*/documentation/*,*/error.html,/config/config.js"

rest:
  client:
    access-sphere:
      client-id: TAX-CALCULATOR-TEST-01
      baseUrl: http://localhost:8081
      userInfo: /v1/userInfo

logging:
  config: classpath:logback-google.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    io.github.giovannilamarmora.tax_calculator: DEBUG
    io.github.giovannilamarmora.utils: DEBUG
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR